# -*- coding: utf-8 -*-
"""Copia de Cotizador_PNR_Amadeus.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TvKxHyipYZxf7-1x7EK-rOuN5qOH5Ofq

# Cotizador Aéreos

## Dos flujos distintos:

- Cabotaje
- Internacional
- Internacional saliendo fuera de Argentina

----

# Script para cotizar aéreos
## TIPS

- Remarcar la diferencia con Despegar
- Abonando en USD tiene descuento
- Foto de Pasaportes y visa (no tomamos reservas sin esto)
- Equipaje en cabina y en bodega
- Remarcar LTD (ultimo momento para emitir)
- Seguro de Asistencia
- Auto
"""

# Diccionarios a utilizar

aeropuertos = {
    "ADD": "Addis Ababa, Ethiopia",
    "ADZ": "San Andrés",
    "AEP": "Aeroparque, Buenos Aires",
    "AKL": "Auckland, New Zeland",
    "ALC": "Alicante",
    "AMS": "Amsterdam, Países Bajos",
    "ASU": "Asunción, Paraguay",
    "ATH": "Atenas, Grecia",
    "ATL": "Atlanta, USA",
    "AUA": "Aruba",
    "AVV": "Melbourne, Australia",
    "BHI": "Bahia Blanca",
    "BCN": "Barcelona",
    "BOG": "Bogotá",
    "BRC": "San Carlos de Bariloche",
    "BUE": "Buenos Aires",
    "CDG": "Charles De Gaulle, París",
    "CGH": "Congonhas, Sao Paulo",
    "CJC": "Calama, Chile",
    "COR": "Córdoba",
    "CPC": "San Martín de los Andes",
    "CTG": "Cartagena de Indias",
    "CUN": "Cancún",
    "CUR": "Curazao, Antillas Holandesas",
    "CUZ": "Cuzco",
    "EWR": "Newark New York",
    "EZE": "Ezeiza, Buenos Aires",
    "FCO": "Fiumicino, Roma",
    "FLN": "Florianópolis",
    "FRA": "Frankfurt",
    "FTE": "El Calafate",
    "GIG": "El Galeao, Rìo de Janeiro",
    "GLA": "Glasgow, Escocia",
    "GRU": "Guarulhos, Sao Paulo",
    "GUA": "Ciudad de Guatemala",
    "GYE": "Guayaquil, Ecuador",
    "HAV": "La Habana, Cuba",
    "HOU": "Houston, Texas",
    "IAH": "Houston, Texas, USA",
    "IGR": "Puerto Iguazú, Argentina",
    "IGU": "Foz do Iguazu, BR",
    "IQQ": "Iquique, Chile",
    "IST": "Istambul, Turkey",
    "JFK": "John F. Kenedy New York",
    "JUJ": "Jujuy",
    "LAP": "La Paz, Mexico",
    "LAS": "Las Vegas",
    "LAX": "Los Angeles, California",
    "LGA": "La Guardia New York",
    "LGW": "London",
    "LHR": "Heathrow, London",
    "LIM": "Lima, Perú",
    "LIS": "Lisboa",
    "MAD": "Madrid",
    "MCO": "Orlando, Florida, US",
    "MDZ": "Mendoza",
    "MDQ": "Mar del Plata",
    "MEC": "Manta, Ecuador",
    "MEL": "Melbourne, Australia",
    "MEX": "México DF",
    "MIA": "Miami, USA",
    "MIL": "Milano",
    "MXP": "Malpensa, Milano",
    "NLU": "Felipe Angeles, Mexico DF",
    "ORD": "Chicago, USA",
    "ORY": "Orly, París",
    "POA": "Porto Allegre",
    "PMI": "Palma de Mallorca, Islas Baleares, España",
    "PTY": "Panamá",
    "ROS": "Rosario",
    "PUJ": "Punta Cana",
    "RDD": "Readding, California",
    "SCL": "Santiago de Chile",
    "SDQ": "Santo Domingo, Repùblica Dominicana",
    "SDU": "Santos Dumont Rio de Janeiro",
    "SFO": "San Francisco, California",
    "SJD": "Los Cabos, Mexico",
    "SLA": "Salta",
    "SMR": "Santa Marta, Colombia",
    "SSA": "Salvador, Bahia",
    "SVQ": "Sevilla",
    "SYD": "Sydney",
    "TIJ": "Tijuana, Mexico",
    "UIO": "Quito, Ecuador",
    "USH": "Ushuaia",
    "VLC": "Valencia, España",
    "VVI": "Santa Cruz de la Sierra, Bolivia"
}

lineas = {
    "AR": "Aerolíneas Argentinas",
    "CM": "Copa Airlines",
    "LA": "Latam",
    "KL": "KLM, Royal Dutch Airlines",
    "AA": "American Airlines",
    "DL": "Delta Airlines",
    "UX": "Air Europa",
    "IB": "Iberia",
    "AF": "Air France",
    "UA": "United Airlines",
    "G3": "Gol Lihnas Aereas",
    "WJ": "Jet Smart",
    "OB": "Boliviana de Aviación",
    "H2": "Sky Airlines",
    "ET": "Ethiopian Airlines",
    "JA": "Jetsmart Spa"
}

# 0P|20|30|32|2B|PC|1P|2P|3P
franquicia = {
    "0P": "Solo 1 carryon de 10 kg. en cabina, sin equipaje en bodega",
    "1P": "Carryon de 10 kg. en cabina + una maleta despachada en bodega de 23kg",
    "2P": "Carryon de 10 kg. en cabina + dos maletas despachadas en bodega de 23kg c/u",
    "30": "Carryon de 10 kg. en cabina + una maleta despachada en bodega de 30kg",
    "3P": "Carryon de 10 kg. en cabina + tres maletas despachadas en bodega de 23kg c/u"
}

devoluciones = {
    "NON-REF": "No permite devoluciones ni cambios",
    "NON-END": "No permite devoluciones ni cambios"
}

financiacion = {
    "AR": "https://www.aerolineas.com.ar/es-ar/reservasservicios/bancos",
    "WJ":"https://jetsmart.com/ar/es/minisitios/medios-de-pago"
}

cabecera = {
    "th": "\n*TURISMO Y HOTELERÍA CONSULTORA*\nwww.thconsultora.com.ar | email: marco@thconsultora.com.ar |\
 Tel/Wp: +543513070654",
    "gr": "\n*GRIFFIN VIAJES* | Leg. 10659 | San Jeronimo 167 Local 16 Gal. Saint Michell\nwww.griffinviajes.com.ar | email: aulavirtualturismo.com.ar |\
 cel/Wp: +543513070654 | Tel: +543514245547 ",
    "pa":"\n*Pampero Viajes y Turismo | EVT Leg 18042* | \nAviador Richardson 2150 1ºA - Córdoba | Tel: 3515190438 | Mail: pamperoviajesyturismo@gmail.com",
    "ni":"\n*TRIBU TRAVEL TOUR* | Leg. 18163 \nhttps://tribu-travel-tour.misitiosimple.com/\nAvellaneda 534 Alta Gracia | Tel/Wp:3513019736"
}

# Pegamos el texto que copiamos en el modo Gráfico
gra = '''
N.º	Vuelo	Clase	Fecha	De	a	Hora de salida	Hora de llegada	Avión	Duración
1.	LA 487	N - Turista	12JUL24	COR
A.l.v. Taravella	SCL
T2 - A. Merino Benítez	19:30	20:12	Airbus A321	21h20
2.	LA 2370	N - Turista	13JUL24	SCL
T2 - A. Merino Benítez	LIM
Jorge Chávez Internacional	04:15	07:00	Airbus A320
3.	LA 2410	N - Turista	13JUL24	LIM
Jorge Chávez Internacional	HAV
Jose Marti Internacional	09:25	15:50	Airbus A320
4.	LA 2411	Q - Turista	20JUL24	HAV
Jose Marti Internacional	LIM
Jorge Chávez Internacional	17:25	21:40	Airbus A320	24h20
5.	LA 635	Q - Turista	21JUL24	LIM
Jorge Chávez Internacional	SCL
T2 - A. Merino Benítez	08:30	13:00	Boeing 787-8
6.	LA 486	Q - Turista	21JUL24	SCL
T2 - A. Merino Benítez	COR
A.l.v. Taravella	16:15	18:45	Airbus A320

DDMMMYYYY
Correo electrónico :

Teléfono :

Detalles de Pago (1)
Forma de pago
Seleccione...
Dirección de facturación (1)
Nueva dirección...


Información sobre precios (2)
Precio total que debe pagarse: 849984.00 ARS (Para todos los pasajeros, con impuestos y descuento)
#	PTC	Tarifa	Tasa	Total pendiente de pago
1.	ADT	154972.00 ARS	695012.00 ARS	849984.00 ARS
Total		154972.00 ARS	695012.00 ARS	849984.00 ARS
'''

# Abrimos el archivo pnr.txt en modo lectura solamente
# lo leemos
# con print nos aseugramos de ver el contenido

tst = '''
FFXR

01 P1
NO REBOOKING REQUIRED FOR LOWEST AVAILABLE FARE
LAST TKT DTE 15MAR24/00:29 LT in POS - SEE ADV PURCHASE
------------------------------------------------------------
     AL FLGT  BK T DATE  TIME  FARE BASIS      NVB  NVA   BG
 COR
XLIM LA  2365 S  S 19APR 0805  SLEKM50I        19APR19APR 1P
 MAD LA  1605 S  S 19APR 1140  SLEKM50I        19APR19APR 1P
XSCL LA   705 Q  Q 02MAY 2355  QLESL58I        02MAY02MAY 0P
 COR LA   486 Q  Q 03MAY 1615  QLESL58I        03MAY03MAY 0P

USD  1011.00      19APR24COR LA X/LIM LA MAD M571.00LA X/SCL
ARS878054.00      LA COR M440.00NUC1011.00END ROE1.00
ARS 64381.90-AR   XT ARS 275922.60-O5 ARS 275922.60-Q1 ARS
ARS 41688.00-YR   8685.00-QO ARS 1215.90-S7 ARS 6948.00-TQ
ARS641482.00-XT   ARS 49504.50-XR ARS 19330.10-JD ARS 597.30
AR1625605.90      -OG ARS 3356.00-QV
RATE USED 1USD=868.50ARS
NO BAG INCLUDED FOR AT LEAST ONE FLIGHT
>                                                 PAGE  2/ 3
>
m
FARE FAMILIES:    (ENTER FQFN FOR DETAILS, FXY FOR UPSELL)
FARE FAMILY:FC1:1-2:KM
FARE FAMILY:FC2:3-4:SL
FXU/TS TO UPSELL KM-KM FOR 59465.40ARS
TICKET STOCK RESTRICTION
BG CXR: 2*LA/2*LA
PRICED WITH VALIDATING CARRIER LA - REPRICE IF DIFFERENT VC
TICKETS ARE NON-REFUNDABLE
ENDOS NONEND-REF/CHG SEE PENALTY
>                                                 PAGE  3/ 3
>
rt
--- MSC ---
RP/CORG121EU/
  1  LA2365 S 19APR 5*CORLIM DK1  0805 1000  19APR  E  0 320 B
     010 DL 6084
     101 WPRYBHKMLVXSNQOGTAE
     127 LATAM AIRLINES PERU
     OPERATED BY SUBSIDIARY/FRANCHISE
     SEE RTSVC
  2  LA1605 S 19APR 5*LIMMAD DK1  1140 0610  20APR  E  0 359 LS
     050 IB 6652
     127 IBERIA FOR LATAM AIRLINES GROUP
     OPERATED BY SUBSIDIARY/FRANCHISE
     SEE RTSVC
  3  LA 705 Q 02MAY 4*MADSCL DK1  2355 0720  03MAY  E  0 789 DB
     SEE RTSVC
  4  LA 486 Q 03MAY 5*SCLCOR DK1  1615 1845  03MAY  E  0 320 S
     SEE RTSVC
>
'''

print(tst)

# Captura datos
# Importamos la librería RE, definimos un fee por defecto
# y preguntamos al usuario si quiere cambiarlo
import re
fee = 46000
blue = 494
cabe = input("\n---------------------------------------\nDefinir Cabecera th, ni, gr, pa: ")
cabe = cabe.lower()
fee = int(input("\n-------------------------------------\nDefinir fee en ARS oficial\nPor defecto es ARS46000: "))
blue = int(input("\n-------------------------------------\nIndicar el tipo de cambio blue Vendedor: "))
ventausd = int(input("\n----------------------------------\nIndicar el precio en USD emitiendo en MIA: "))

"""
## Cotizacion Internacional INICIADOS EN ARGENTINA
### Versión Criptico


---"""

# Desmenuzamos el archivo buscando los campos puntuales con expresiones regulares

pos_carrier=tst.find('CARRIER')
cia=tst[(pos_carrier+8):(pos_carrier+10)]
cambio=re.findall('1USD=(......)', tst)
route = re.findall(r'^\s{2}\d{1}\s{2}\w{2}.{53}',tst, flags=re.M)
orig = re.findall('\n (\w{3})\n', tst)[0]
fare_ars = re.findall('\nARS(\D{0,3}\d{1,6}.\d{2})', tst)[0][1]
bagage = re.findall(' (0P|20|30|32|2B|PC|1P|2P|3P)\n', tst)[0]
ltd = re.findall('(DTE \d{2}\D{3}\d{2}/\d{2}:\d{2}|DTE \d{2}\D{3}\d{2})', tst)[0]
date = re.findall(r'(?:[ |*][A-Z]{1}.)((?:\d{2}\D{3} ))', tst)
ttl = re.findall('\n(ARS|AR|ARS )(\d{1,7}.\d{2})', tst)[-1][-1]
ref = re.findall('\n(ENDOS|NONREF|NON-REF|NON|TICKETS)', tst)[0]
retenc = re.findall('(\d{0,6}.\d{2})(Q1 |-Q1 )', tst)
#fare_usd = re.findall('USD(\D{0,6}\d{1,6}.\d{2}) ', tst)[0]

# Los tramos los tomamos del frente del PNR y los recortamos para obtener solo la info relevante
tramo=[]
clases=[]
contador = len(route)

for renglon in route:
    vuelo = renglon[5:12]
    clase = renglon[12:13]
    fecha = renglon[14:20]
    horarios = renglon[34:44]
    #orides = renglon[22:29]
    ori = renglon[22:25]
    des = renglon[25:28]
    tramo.append(vuelo+fecha+aeropuertos.get(ori) + " / " + aeropuertos.get(des)+" "+horarios)
    clases.append(clase)
    contador = contador-1

# Juntamos toda la info de los tramos
tramos="\n".join(tramo)
clases="".join(clases)

# Agregamos el Fee al total del PNR
total=float(ttl)+float(fee)

totalblue = float(total) / float(blue)
totalmia = (float(fee) / float(blue)) + float(((ventausd)*.999)+5)

# Escribimos el resultado
texto =(f'{cabecera.get(cabe)}\n--------------------------------------------\nCotización Internacional iniciando vuelos en Argentina - NO ES RESERVA\n* Compañia \
 Emisora: {str(lineas.get(cia))}\n* Origen: {str(aeropuertos.get(orig))}\n\n* Despliegue de vuelos en horarios\
 locales\n{str(tramos)}\n\n* Ultimo día para emitir: {str(ltd)}\n* Equipaje \
 incluido: {str(franquicia.get(bagage))}\n**Total con impuestos PAGANDO EN PESOS ARS: {str(total)} por pasajero*\n* Cambios y Devoluciones: {str(devoluciones.get(ref))}\n* Cash o\
 tarjeta de crédito en 1 cuota solamente\n**Emitiendo en dólares físicos IMPECABLES cara \
 grande USD {str(int(totalmia))}* / Ahorras USD{str(int(totalblue)-int(totalmia))} emitiendo en Dólares*\n* Tomamos reserva solo con foto de DNI o \
 Pasaporte\n* Recomendamos llevar asistencia al viajero ver opciones aqui -> https://www.thconsultora.com.ar/shop \n {str(clases)}{str(int(fee/blue))}')

print(texto)

# Desmenuzamos el archivo buscando los campos puntuales con expresiones regulares
# Version grafico

# pos_carrier=gra.find('CARRIER')
# cia=tst[(pos_carrier+8):(pos_carrier+10)]
# cambio=re.findall('1USD=(......)', tst)
route = re.findall(r'^[1-9]\.\t[A-Z1-9]{2}',gra, flags=re.M)
# orig = re.findall('\n (\w{3})\n', gra)[0]
# fare_ars = re.findall('pagarse: ', tst)[0][1]
# bagage = re.findall(' (0P|20|30|32|2B|PC|1P|2P|3P)\n', tst)[0]
# ltd = re.findall('(DTE \d{2}\D{3}\d{2}/\d{2}:\d{2}|DTE \d{2}\D{3}\d{2})', tst)[0]
# date = re.findall(r'(?:[ |*][A-Z]{1}.)((?:\d{2}\D{3} ))', tst)
ttl = re.findall('pagarse: (\d{1,7}.\d{2})', gra)[-1][-1]
# ref = re.findall('\n(ENDOS|NONREF|NON-REF|NON|TICKETS)', tst)[0]
# retenc = re.findall('(\d{0,6}.\d{2})(Q1 |-Q1 )', tst)
#fare_usd = re.findall('USD(\D{0,6}\d{1,6}.\d{2}) ', tst)[0]

# Los tramos los tomamos del frente del PNR y los recortamos para obtener solo la info relevante
tramo=[]
clases=[]
contador = len(route)

for renglon in route:
    vuelo = renglon[5:12]
    clase = renglon[12:13]
    fecha = renglon[14:20]
    horarios = renglon[34:44]
    #orides = renglon[22:29]
    ori = renglon[22:25]
    des = renglon[25:28]
    tramo.append(vuelo+fecha+horarios+aeropuertos.get(ori) + " / " + aeropuertos.get(des))
    clases.append(clase)
    contador = contador-1

# Juntamos toda la info de los tramos
tramos="\n".join(tramo)
clases="".join(clases)

# Agregamos el Fee al total del PNR
total=float(ttl)+float(fee)

totalblue = float(total) / float(blue)
totalmia = (float(fee) / float(blue)) + float(((ventausd)*.80)+5)

# Escribimos el resultado
texto =(f'{cabecera.get(cabe)}\n--------------------------------------------\nCotización Internacional iniciando vuelos en Argentina - NO ES RESERVA\n* Compañia \
 \n\n* Despliegue de vuelos en horarios \
 locales\n* Cia/Vuelo | Fecha | Sale | Llega | Origen | Destino \n{str(tramos)}\
 \n* Tipo de Cambio USD blue: {str(blue)}\
 \n**Total con impuestos ARS: {str(total)} por pasajero* \
 cash o tarjeta de crédito en 1 cuota solamente\n* Equivalente Dólares al blue USD: {str(int(totalblue))}\n**Emitiendo en billetes físicos cara \
 grande USD {str(int(totalmia))}* / Ahorras USD{str(int(totalblue)-int(totalmia))} emitiendo en Dólares*\n* Tomamos reserva solo con foto de DNI o \
 Pasaporte\n* Recomendamos llevar asistencia al viajero ver opciones aqui -> https://www.thconsultora.com.ar/shop \n {str(clases)}')

print(texto)
